spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml
    parameters:
      schema: STUDY_JOURNAL
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;INIT=CREATE SCHEMA IF NOT EXISTS "STUDY_JOURNAL"
    username: sa
    password:
    hikari:
      schema: STUDY_JOURNAL
