name: Test

on:
  pull_request:
      - '*'
  push:
    branches:
      - '*'

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        run: ./gradlew clean test
      - name: Integration tests
        run: ./gradlew clean integrationTest
