server:
  port: 8080
  servlet:
    context-path: /api

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml
    parameters:
      schema: study_journal
  datasource:
    url: jdbc:postgresql://localhost:5432/study_journal_database
    username: root
    password: 123123
    hikari:
      schema: study_journal
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "study_journal";

security:
  jwt:
    token:
      expire-length: 600000