server:
  port: 8080
  servlet:
    context-path: /metadata-generator

spring:
  liquibase:
    enabled: false
#    change-log: classpath:/db/liquibase/changelog.xml
#    parameters:
#      schema: study_table
#    url: jdbc:postgresql://localhost:5432/study_table_databse
#    user: root
#    password: 123123
#  datasource:
#    hikari:
#      schema: study_table
#      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "study_table";
