name: Build

on: push

jobs:
  push:
    name: Backend push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        working-directory: ./study-journal-back
        run: ./gradlew clean assemble
      - name: Tests
        working-directory: ./study-journal-back
        run: ./gradlew clean test
      - name: Integration tests
        working-directory: ./study-journal-back
        run: ./gradlew clean integrationTest