name: Build

on: push

jobs:
  backend-tests:
    name: Backend build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: cd study-journal-back && ./gradlew clean build
