name: Test

on: push

jobs:
  backend-tests:
    name: Backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tests
        run: cd study-journal-back && ./gradlew clean test
      - name: Integration tests
        run: cd study-journal-back &&./gradlew clean integrationTest
