name: Test

on: push
jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        run: ./gradlew clean test
      - name: Integration tests
        run: ./gradlew clean integrationTest
